//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adres()
        {
            this.pacjent = new HashSet<pacjent>();
            this.lekarz = new HashSet<lekarz>();
        }
    
        public int id_adres { get; set; }
        public string kraj { get; set; }
        public string wojewodztwo { get; set; }
        public string miasto { get; set; }
        public string kod_pocztowy { get; set; }
        public string ulica { get; set; }
        public Nullable<int> nr_budynku { get; set; }
        public Nullable<int> nr_domu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pacjent> pacjent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lekarz> lekarz { get; set; }
    }
}
