//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class badanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public badanie()
        {
            this.wizyta = new HashSet<wizyta>();
        }
    
        public int id_badanie { get; set; }
        public Nullable<int> id_lekarz { get; set; }
        [DisplayName("Numer pacjenta")]
        public Nullable<int> id_pacjent { get; set; }
        [DisplayName("Opis badania")]
        public string opis_badania { get; set; }
        [DisplayName("Data badania")]
        public Nullable<System.DateTime> data_badania { get; set; }
        [DisplayName("Nazwisko lekarza")]
        public virtual lekarz lekarz { get; set; }
        [DisplayName("Nazwisko pacjenta")]
        public virtual pacjent pacjent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wizyta> wizyta { get; set; }
    }
}
