//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class choroba_view
    {
        public string id_uzytkownika { get; set; }
        public string nazwisko { get; set; }
        public string nazwa_choroby { get; set; }
        public string diagnoza { get; set; }
        public string objawy { get; set; }
        public int id_pacjent { get; set; }
        public int id_choroba { get; set; }
    }
}
