//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ePrzychodniaEntities : DbContext
    {
        public ePrzychodniaEntities()
            : base("name=ePrzychodniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		modelBuilder.Conventions.Remove<System.Data.Entity.ModelConfiguration.Conventions.PluralizingTableNameConvention>();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<badanie> badanie { get; set; }
        public virtual DbSet<choroba> choroba { get; set; }
        public virtual DbSet<godziny_przyjec> godziny_przyjec { get; set; }
        public virtual DbSet<lekarz> lekarz { get; set; }
        public virtual DbSet<pacjent> pacjent { get; set; }
        public virtual DbSet<recepta> recepta { get; set; }
        public virtual DbSet<skierowanie> skierowanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<wizyta> wizyta { get; set; }
        public virtual DbSet<choroba_view> choroba_view { get; set; }
        public virtual DbSet<badania_view> badania_view { get; set; }
        public virtual DbSet<recepta_view> recepta_view { get; set; }
        public virtual DbSet<skierowanie_view> skierowanie_view { get; set; }
    }
}
