//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class godziny_przyjec
    {
        public int id_godziny_przyjec { get; set; }
        public Nullable<int> id_pracownik { get; set; }
        public string dzien_tygodnia { get; set; }
        public Nullable<System.DateTime> godz_od { get; set; }
        public Nullable<System.DateTime> godz_do { get; set; }
    
        public virtual lekarz lekarz { get; set; }
    }
}
