//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lekarz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lekarz()
        {
            this.badanie = new HashSet<badanie>();
            this.godziny_przyjec = new HashSet<godziny_przyjec>();
            this.recepta = new HashSet<recepta>();
        }
    
        public int id_lekarz { get; set; }
        public string nazwisko { get; set; }
        public string imie { get; set; }
        public string pesel { get; set; }
        public string telefon { get; set; }
        public string id_uzytkownika { get; set; }
        public string UserRoles { get; set; } = "Lekarz";
        public string Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<badanie> badanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<godziny_przyjec> godziny_przyjec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepta> recepta { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
