//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class recepta_view
    {
        public string id_uzytkownika { get; set; }
        [DisplayName("Numer recepty")]
        public int Numer_recepty { get; set; }
        [DisplayName("Data wystawienia")]
        public Nullable<System.DateTime> Data_wystawienia { get; set; }
        [DisplayName("Leki i dawkowanie")]
        public string Nazwa_leku_i_dawkowanie { get; set; }
    }
}
