//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skierowanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skierowanie()
        {
            this.wizyta = new HashSet<wizyta>();
        }
    
        public int id_skierowanie { get; set; }
        public Nullable<int> id_pacjent { get; set; }
        public Nullable<int> id_badanie { get; set; }
        public Nullable<int> id_lekarz { get; set; }
        public Nullable<System.DateTime> data_wystawienia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wizyta> wizyta { get; set; }
    }
}
