//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skierowanie_view
    {
        public string id_uzytkownika { get; set; }
        public int Numer_skierowania { get; set; }
        public string C_Nazwisko_lekarza { get; set; }
        public Nullable<System.DateTime> Data_wystawienia { get; set; }
    }
}
