//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wizyta
    {
        public int id_wizyta { get; set; }
        public Nullable<int> id_skierowanie { get; set; }
        public Nullable<int> id_recepta { get; set; }
        public Nullable<int> id_choroba { get; set; }
        public Nullable<int> id_badanie { get; set; }
        public Nullable<int> id_lekarz { get; set; }
        public Nullable<int> id_pacjent { get; set; }
        public Nullable<System.DateTime> data_wizyty { get; set; }
    
        public virtual badanie badanie { get; set; }
        public virtual choroba choroba { get; set; }
        public virtual recepta recepta { get; set; }
        public virtual skierowanie skierowanie { get; set; }
    }
}
