//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePrzychodnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapis
    {
        public int id_zapisu { get; set; }
        public Nullable<int> id_pacjenta { get; set; }
        public Nullable<int> id_lekarza { get; set; }
        public DateTime? data { get; set; }
        public TimeSpan? godzina { get; set; }
    
        public virtual lekarz lekarz { get; set; }
        public virtual pacjent pacjent { get; set; }
    }
}
